import Foundation
import SwiftData
import TutorCore

@Model
public final class Flashcard {
    public var id: UUID = UUID()
    public var front: String = ""
    public var back: String = ""
    public var isAutoGenerated: Bool = true
    public var createdAt: Date = Date()

    // FSRS spaced repetition fields
    public var difficulty: Double = 0.3
    public var stability: Double = 0.0
    public var dueDate: Date = Date()
    public var lastReviewDate: Date?
    public var reviewCount: Int = 0
    public var lapseCount: Int = 0
    public var state: String = CardState.new.rawValue

    // Relationships
    public var sourceItem: KnowledgeItem?

    @Relationship(deleteRule: .cascade, inverse: \FlashcardReview.flashcard)
    public var reviews: [FlashcardReview]?

    public init(front: String, back: String, isAutoGenerated: Bool = true) {
        self.id = UUID()
        self.front = front
        self.back = back
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = Date()
        self.dueDate = Date()
    }

    public var cardState: CardState {
        get { CardState(rawValue: state) ?? .new }
        set { state = newValue.rawValue }
    }

    /// Whether this card is due for review
    public var isDue: Bool {
        dueDate <= Date()
    }
}
